=== LilyGS94/sumo_graph/test/test_data/rikishi_test_response_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "id": { "type": "number" },
    "sumodbId": { "type": "number" },
    "nskId": { "type": "number", "optional": true },
    "shikonaEn": { "type": "string" },
    "shikonaJp": { "type": "string", "optional": true },
    "currentRank": { "type": "string", "optional": true },
    "heya": { "type": "string" },
    "birthDate": { "type": "string", "format": "date-time" },
    "shusshin": { "type": "string" },
    "height": { "type": "number" },
    "weight": { "type": "number" },
    "debut": { "type": "string" },
    "intai": { "type": "string", "format": "date-time", "optional": true }
  },
  "required": ["id", "sumodbId", "shikonaEn", "heya", "birthDate", "shusshin", "height", "weight", "debut"]
}

=== LilyGS94/sumo_graph/data/202509/rikishi/38.json
{"id": 38, "sumodbId": 11946, "nskId": 3337, "shikonaEn": "Meisei", "shikonaJp": "\u660e\u751f\u3000\u529b", "currentRank": "Maegashira 13 East", "heya": "Tatsunami", "birthDate": "1995-07-24T00:00:00Z", "shusshin": "Kagoshima-ken, Oshima-gun, Setouchi-cho", "height": 180, "weight": 152, "debut": "201105"}

=== LilyGS94/sumo_graph/data/202509/rikishi/73.json
{"id": 73, "sumodbId": 11918, "nskId": 3312, "shikonaEn": "Akua", "shikonaJp": "\u5929\u7a7a\u6d77(\u3042\u304f\u3042)", "currentRank": "Makushita 13 West", "heya": "Tatsunami", "birthDate": "1990-11-06T00:00:00Z", "shusshin": "Ibaraki-ken, Higashiibaraki-gun, Oarai-machi", "height": 185.1, "weight": 172.3, "debut": "201011"}

=== LilyGS94/sumo_graph/data/202312/rikishi/109.json
{"id": 109, "sumodbId": 8900, "nskId": 3056, "shikonaEn": "Akiseyama", "shikonaJp": "\u660e\u702c\u5c71", "currentRank": "Makushita 6 West", "heya": "Kise", "birthDate": "1985-07-18T00:00:00Z", "shusshin": "Aichi-ken, Kasugai-shi", "height": 182, "weight": 183, "debut": "200801", "intai": "2023-08-10T00:00:00Z"}

=== LilyGS94/sumo_graph/data/202312/rikishi/12.json
{"id": 12, "sumodbId": 12370, "nskId": 3761, "shikonaEn": "Wakatakakage", "shikonaJp": "\u82e5\u9686\u666f\u3000\u6e25", "currentRank": "Makushita 1 West", "heya": "Arashio", "birthDate": "1994-12-06T00:00:00Z", "shusshin": "Fukushima-ken, Fukushima-shi", "height": 180, "weight": 129, "debut": "201703"}

=== LilyGS94/sumo_graph/data/202312/rikishi/26.json
{"id": 26, "sumodbId": 12210, "nskId": 3620, "shikonaEn": "Mitakeumi", "shikonaJp": "\u5fa1\u5dbd\u6d77\u3000\u4e45\u53f8", "currentRank": "Maegashira 9 West", "heya": "Dewanoumi", "birthDate": "1992-12-25T00:00:00Z", "shusshin": "Nagano-ken, Kiso-gun, Agematsu-machi", "height": 179, "weight": 172, "debut": "201503"}

=== LilyGS94/sumo_graph/data/202509/rikishi/32.json
{"id": 32, "sumodbId": 12406, "nskId": 3797, "shikonaEn": "Mitoryu", "shikonaJp": "\u6c34\u6238\u9f8d(\u307f\u3068\u308a\u3085\u3046)", "currentRank": "Makushita 7 West", "heya": "Nishikido", "birthDate": "1994-04-25T00:00:00Z", "shusshin": "Mongolia, Ulaanbaatar", "height": 190, "weight": 195, "debut": "201703"}

=== LilyGS94/sumo_graph/data/202509/rikishi/8850.json
{"id": 8850, "sumodbId": 12836, "nskId": 4227, "shikonaEn": "Onosato", "shikonaJp": "\u5927\u306e\u91cc\u3000\u6cf0\u8f1d", "currentRank": "Yokozuna 1 East", "heya": "Nishonoseki", "birthDate": "2000-06-07T00:00:00Z", "shusshin": "Ishikawa-ken, Kahoku-gun, Tsubata-machi", "height": 192, "weight": 183, "debut": "202305"}

=== LilyGS94/sumo_graph/data/202509/rikishi/64.json
{"id": 64, "sumodbId": 12273, "nskId": 3665, "shikonaEn": "Daiamami", "shikonaJp": "\u5927\u5944\u7f8e(\u3060\u3044\u3042\u307e\u307f)", "currentRank": "Makushita 1 East", "heya": "Oitekaze", "birthDate": "1992-12-15T00:00:00Z", "shusshin": "Kagoshima-ken, Oshima-gun, Tatsugo-cho", "height": 185, "weight": 190, "debut": "201601"}
